import type { Metadata } from 'next';
import './globals.css';
import { MSWComponent } from './_component/MSWComponent';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<MSWComponent />
				{children}
			</body>
		</html>
	);
}
