import type { Metadata } from 'next';
import './globals.css';
import AuthSession from '../context/AuthSessionProvider';
import { MSWComponent } from '../context/MSWComponent';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{/* MSW mock server api 사용 */}
				<MSWComponent />
				{/* next-auth session 사용 */}
				<AuthSession>{children}</AuthSession>
			</body>
		</html>
	);
}
